---
name: Continuous Integration - ACR-K8s
on:
  # pull_request:
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      terraform_cli_version:
        description: 'Terraform CLI Version'
        required: true
        default: 'latest'
        type: string

jobs:
  validate_and_plan:
    uses: jluris-enterprise/alz-mgmt/.github/workflows/ci-acr-k8s-template.yaml@main
    name: 'CI'
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    with:
      root_module_folder_relative_path: 'workloads/acr-k8s/dev'
      terraform_cli_version: ${{ inputs.terraform_cli_version }}
