---
name: Continuous Integration - ALZ Management Runners
on:
  pull_request:
    branches:
      - main
    paths:
      - 'workloads/alz-mgmt-runners/**'
      - '.github/workflows/ci-alz-mgmt-runners*.yaml'
      - '.github/workflows/cd-alz-mgmt-runners*.yaml'
  workflow_dispatch:
    inputs:
      terraform_cli_version:
        description: Terraform CLI Version
        required: true
        default: 1.14.8
        type: string

jobs:
  validate_and_plan:
    uses: ./.github/workflows/ci-alz-mgmt-runners-template.yaml
    name: CI
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    with:
      root_module_folder_relative_path: workloads/alz-mgmt-runners
      terraform_cli_version: ${{ inputs.terraform_cli_version || '1.14.8' }}
      backend_state_key: alz-mgmt-runners.tfstate
